server {
    listen 80;

    location = / {
        return 301 /brain_dump_and_sort/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /brain_dump_and_sort/index.html;
    }

    error_page 404 /brain_dump_and_sort/index.html;
}
